{% set name = "openml" %}
{% set version = "0.12.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cefb4792ca12ee87ab3acc5e5afb4e9d205c398621e2424f2f5de1564cfee849

build:
  number: 1
  noarch: python
  entry_points:
    - openml=openml.cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<36]

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - wheel
  run:
    - python >=3.6
    - liac-arff >=2.4.0
    - xmltodict
    - requests
    - scikit-learn >=0.18
    - python-dateutil
    - pandas >=1.0.0
    - scipy >=0.13.3
    - minio
    # AttributeError: `np.sctypes` was removed in the NumPy 2.0 release. Access dtypes explicitly instead.
    - numpy >=1.6.2,<2
    - pyarrow

test:
  imports:
    - openml
    - openml.datasets
  commands:
    - pip check
    - openml --help
  requires:
    - pip

about:
  home: https://openml.org
  summary: Python API for OpenML
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: |
    OpenML-Python provides an easy-to-use and straightforward Python interface for OpenML,
    an online platform for open science collaboration in machine learning.
    It can download or upload data from OpenML, such as datasets and machine learning experiment results.
  dev_url: https://github.com/openml/openml-python
  doc_url: https://openml.github.io/openml-python

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
